# Generated by Django 4.1.7 on 2023-06-11 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='propscanuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='broker',
            name='email',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='propscanuser',
            name='email_id',
        ),
        migrations.AddField(
            model_name='buyer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propscanuser',
            name='full_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='additional_phone_no_1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='additional_phone_no_2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='company_address_2',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='company_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='broker',
            name='landline_number_1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='landline_number_2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='rera_registered',
            field=models.CharField(choices=[('Yes', 'Yes'), ('Applied', 'I have applied'), ('NotApplicable', 'Not Applicable')], max_length=20),
        ),
        migrations.AlterField(
            model_name='broker',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propscanuser',
            name='user_type',
            field=models.CharField(choices=[('BUYER', 'BUYER'), ('OWNER', 'OWNER'), ('BROKER', 'BROKER')], default='BUYER', max_length=10),
        ),
    ]
