# Generated by Django 4.2.1 on 2023-06-15 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_propscanuser_managers_remove_broker_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='additional_phone_no_1',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator('^\\+91\\d{10}$', code='invalid_phonenumber', message="Phone number must be entered in the format: '+919876543210'. '+91' followed by 10 digits")]),
        ),
        migrations.AlterField(
            model_name='broker',
            name='additional_phone_no_2',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator('^\\+91\\d{10}$', code='invalid_phonenumber', message="Phone number must be entered in the format: '+919876543210'. '+91' followed by 10 digits")]),
        ),
        migrations.AlterField(
            model_name='owner',
            name='additional_phone_no',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator('^\\+91\\d{10}$', code='invalid_phonenumber', message="Phone number must be entered in the format: '+919876543210'. '+91' followed by 10 digits")]),
        ),
        migrations.AlterField(
            model_name='propscanuser',
            name='phone_no',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^\\+91\\d{10}$', code='invalid_phonenumber', message="Phone number must be entered in the format: '+919876543210'. '+91' followed by 10 digits")]),
        ),
    ]
