# Generated by Django 4.2.1 on 2023-07-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_broker_additional_phone_no_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='main_image_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
