# Generated by Django 4.2.1 on 2023-06-09 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_listing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertytype3',
            name='possession_expected_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 2, 16, 45, 30, 69769, tzinfo=datetime.timezone.utc)),
        ),
    ]
