# Generated by Django 4.1.7 on 2023-06-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_listing', '0002_alter_propertytype3_possession_expected_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertytype3',
            name='possession_expected_date',
            field=models.DateField(),
        ),
    ]
