# Generated by Django 4.2.1 on 2023-06-18 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_listing', '0004_remove_propertytype2_images_links_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertytype2',
            old_name='images_link',
            new_name='images_links',
        ),
    ]
