# Generated by Django 4.2.1 on 2023-06-18 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_listing', '0005_rename_images_link_propertytype2_images_links'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertytype2',
            old_name='images_links',
            new_name='images_link',
        ),
    ]
