# Generated by Django 4.2.1 on 2023-06-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_listing', '0006_rename_images_links_propertytype2_images_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertytype1',
            name='final_selling_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertytype1',
            name='sold_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertytype2',
            name='final_selling_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertytype2',
            name='sold_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertytype3',
            name='final_selling_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertytype3',
            name='sold_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
