# Generated by Django 4.2.1 on 2023-07-06 09:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('property_listing', '0007_counter_propertytype1_final_selling_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('meet_calls', models.PositiveIntegerField(default=0)),
                ('chat_calls', models.PositiveIntegerField(default=0)),
                ('property_calls', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='propertytype1',
            old_name='images_link',
            new_name='main_image_link',
        ),
        migrations.RenameField(
            model_name='propertytype2',
            old_name='images_link',
            new_name='main_image_link',
        ),
        migrations.RenameField(
            model_name='propertytype3',
            old_name='images_link',
            new_name='main_image_link',
        ),
        migrations.AddField(
            model_name='propertytype1',
            name='additional_images_link',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='propertytype1',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='propertytype1',
            name='propscan_id',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='propertytype1',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='propertytype2',
            name='additional_images_link',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='propertytype2',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='propertytype2',
            name='propscan_id',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='propertytype2',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='propertytype3',
            name='additional_images_link',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='propertytype3',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='propertytype3',
            name='propscan_id',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='propertytype3',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
