# Generated by Django 4.2.1 on 2023-07-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_listing', '0008_counter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertytype2',
            name='bhk',
        ),
        migrations.RemoveField(
            model_name='propertytype2',
            name='no_of_bathrooms',
        ),
        migrations.RemoveField(
            model_name='propertytype2',
            name='no_of_bedrooms',
        ),
        migrations.AddField(
            model_name='propertytype1',
            name='built_up_area',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='propertytype1',
            name='carpet_area',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='propertytype1',
            name='super_built_up_area',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='propertytype2',
            name='bathrooms',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='propertytype2',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='propertytype2',
            name='bhk_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
