# Generated by Django 4.2.1 on 2023-07-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_listing', '0009_remove_propertytype2_bhk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertytype1',
            name='built_up_area',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='propertytype1',
            name='carpet_area',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='propertytype1',
            name='super_built_up_area',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='propertytype2',
            name='bathrooms',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='propertytype2',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
