# Generated by Django 4.2.1 on 2023-07-22 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_listing', '0010_alter_propertytype1_built_up_area_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertytype1',
            options={'verbose_name': 'propertytype1'},
        ),
        migrations.AlterModelOptions(
            name='propertytype2',
            options={'verbose_name': 'propertytype2'},
        ),
        migrations.AlterModelOptions(
            name='propertytype3',
            options={'verbose_name': 'propertytype3'},
        ),
    ]
